// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package p.a;

public final class Demo {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_p_a_UserInfo_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_p_a_UserInfo_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_p_a_LogonRespMessage_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_p_a_LogonRespMessage_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\ndemo.proto\022\003p.a\"I\n\010UserInfo\022\016\n\006acctID\030" +
                        "\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\037\n\006status\030\003 \001(\0162\017.p." +
                        "a.UserStatus\"Z\n\020LogonRespMessage\022%\n\013logo" +
                        "nResult\030\001 \001(\0162\020.p.a.LoginResult\022\037\n\010userI" +
                        "nfo\030\002 \001(\0132\r.p.a.UserInfo*%\n\nUserStatus\022\013" +
                        "\n\007OFFLINE\020\000\022\n\n\006ONLINE\020\001*\240\001\n\013LoginResult\022" +
                        "\030\n\024LOGON_RESULT_SUCCESS\020\000\022\031\n\025LOGON_RESUL" +
                        "T_NOTEXIST\020\001\022\035\n\031LOGON_RESULT_ERROR_PASSW" +
                        "D\020\002\022\036\n\032LOGON_RESULT_ALREADY_LOGON\020\003\022\035\n\031L" +
                        "OGON_RESULT_SERVER_ERROR\020\004b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_p_a_UserInfo_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_p_a_UserInfo_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_p_a_UserInfo_descriptor,
                new java.lang.String[]{"AcctID", "Name", "Status",});
        internal_static_p_a_LogonRespMessage_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_p_a_LogonRespMessage_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_p_a_LogonRespMessage_descriptor,
                new java.lang.String[]{"LogonResult", "UserInfo",});
    }

    private Demo() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    /**
     * Protobuf enum {@code p.a.UserStatus}
     */
    public enum UserStatus
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>OFFLINE = 0;</code>
         */
        OFFLINE(0),
        /**
         * <code>ONLINE = 1;</code>
         */
        ONLINE(1),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>OFFLINE = 0;</code>
         */
        public static final int OFFLINE_VALUE = 0;
        /**
         * <code>ONLINE = 1;</code>
         */
        public static final int ONLINE_VALUE = 1;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                UserStatus> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<UserStatus>() {
                    public UserStatus findValueByNumber(int number) {
                        return UserStatus.forNumber(number);
                    }
                };
        private static final UserStatus[] VALUES = values();
        private final int value;

        private UserStatus(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static UserStatus valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static UserStatus forNumber(int value) {
            switch (value) {
                case 0:
                    return OFFLINE;
                case 1:
                    return ONLINE;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return p.a.Demo.getDescriptor().getEnumTypes().get(0);
        }

        public static UserStatus valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:p.a.UserStatus)
    }

    /**
     * Protobuf enum {@code p.a.LoginResult}
     */
    public enum LoginResult
            implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>LOGON_RESULT_SUCCESS = 0;</code>
         */
        LOGON_RESULT_SUCCESS(0),
        /**
         * <code>LOGON_RESULT_NOTEXIST = 1;</code>
         */
        LOGON_RESULT_NOTEXIST(1),
        /**
         * <code>LOGON_RESULT_ERROR_PASSWD = 2;</code>
         */
        LOGON_RESULT_ERROR_PASSWD(2),
        /**
         * <code>LOGON_RESULT_ALREADY_LOGON = 3;</code>
         */
        LOGON_RESULT_ALREADY_LOGON(3),
        /**
         * <code>LOGON_RESULT_SERVER_ERROR = 4;</code>
         */
        LOGON_RESULT_SERVER_ERROR(4),
        UNRECOGNIZED(-1),
        ;

        /**
         * <code>LOGON_RESULT_SUCCESS = 0;</code>
         */
        public static final int LOGON_RESULT_SUCCESS_VALUE = 0;
        /**
         * <code>LOGON_RESULT_NOTEXIST = 1;</code>
         */
        public static final int LOGON_RESULT_NOTEXIST_VALUE = 1;
        /**
         * <code>LOGON_RESULT_ERROR_PASSWD = 2;</code>
         */
        public static final int LOGON_RESULT_ERROR_PASSWD_VALUE = 2;
        /**
         * <code>LOGON_RESULT_ALREADY_LOGON = 3;</code>
         */
        public static final int LOGON_RESULT_ALREADY_LOGON_VALUE = 3;
        /**
         * <code>LOGON_RESULT_SERVER_ERROR = 4;</code>
         */
        public static final int LOGON_RESULT_SERVER_ERROR_VALUE = 4;
        private static final com.google.protobuf.Internal.EnumLiteMap<
                LoginResult> internalValueMap =
                new com.google.protobuf.Internal.EnumLiteMap<LoginResult>() {
                    public LoginResult findValueByNumber(int number) {
                        return LoginResult.forNumber(number);
                    }
                };
        private static final LoginResult[] VALUES = values();
        private final int value;

        private LoginResult(int value) {
            this.value = value;
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static LoginResult valueOf(int value) {
            return forNumber(value);
        }

        /**
         * @param value The numeric wire value of the corresponding enum entry.
         * @return The enum associated with the given numeric wire value.
         */
        public static LoginResult forNumber(int value) {
            switch (value) {
                case 0:
                    return LOGON_RESULT_SUCCESS;
                case 1:
                    return LOGON_RESULT_NOTEXIST;
                case 2:
                    return LOGON_RESULT_ERROR_PASSWD;
                case 3:
                    return LOGON_RESULT_ALREADY_LOGON;
                case 4:
                    return LOGON_RESULT_SERVER_ERROR;
                default:
                    return null;
            }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<LoginResult>
        internalGetValueMap() {
            return internalValueMap;
        }

        public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
            return p.a.Demo.getDescriptor().getEnumTypes().get(1);
        }

        public static LoginResult valueOf(
                com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
            if (desc.getType() != getDescriptor()) {
                throw new java.lang.IllegalArgumentException(
                        "EnumValueDescriptor is not for this type.");
            }
            if (desc.getIndex() == -1) {
                return UNRECOGNIZED;
            }
            return VALUES[desc.getIndex()];
        }

        public final int getNumber() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalArgumentException(
                        "Can't get the number of an unknown enum value.");
            }
            return value;
        }

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
            if (this == UNRECOGNIZED) {
                throw new java.lang.IllegalStateException(
                        "Can't get the descriptor of an unrecognized enum value.");
            }
            return getDescriptor().getValues().get(ordinal());
        }

        public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
            return getDescriptor();
        }

        // @@protoc_insertion_point(enum_scope:p.a.LoginResult)
    }

    public interface UserInfoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:p.a.UserInfo)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 acctID = 1;</code>
         *
         * @return The acctID.
         */
        long getAcctID();

        /**
         * <code>string name = 2;</code>
         *
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <code>string name = 2;</code>
         *
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString
        getNameBytes();

        /**
         * <code>.p.a.UserStatus status = 3;</code>
         *
         * @return The enum numeric value on the wire for status.
         */
        int getStatusValue();

        /**
         * <code>.p.a.UserStatus status = 3;</code>
         *
         * @return The status.
         */
        p.a.Demo.UserStatus getStatus();
    }

    public interface LogonRespMessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:p.a.LogonRespMessage)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.p.a.LoginResult logonResult = 1;</code>
         *
         * @return The enum numeric value on the wire for logonResult.
         */
        int getLogonResultValue();

        /**
         * <code>.p.a.LoginResult logonResult = 1;</code>
         *
         * @return The logonResult.
         */
        p.a.Demo.LoginResult getLogonResult();

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         *
         * @return Whether the userInfo field is set.
         */
        boolean hasUserInfo();

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         *
         * @return The userInfo.
         */
        p.a.Demo.UserInfo getUserInfo();

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         */
        p.a.Demo.UserInfoOrBuilder getUserInfoOrBuilder();
    }

    /**
     * Protobuf type {@code p.a.UserInfo}
     */
    public static final class UserInfo extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:p.a.UserInfo)
            UserInfoOrBuilder {
        public static final int ACCTID_FIELD_NUMBER = 1;
        public static final int NAME_FIELD_NUMBER = 2;
        public static final int STATUS_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:p.a.UserInfo)
        private static final p.a.Demo.UserInfo DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<UserInfo>
                PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
            @java.lang.Override
            public UserInfo parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new UserInfo(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new p.a.Demo.UserInfo();
        }

        private long acctID_;
        private volatile java.lang.Object name_;
        private int status_;
        private byte memoizedIsInitialized = -1;

        // Use UserInfo.newBuilder() to construct.
        private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private UserInfo() {
            name_ = "";
            status_ = 0;
        }

        private UserInfo(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            acctID_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            name_ = s;
                            break;
                        }
                        case 24: {
                            int rawValue = input.readEnum();

                            status_ = rawValue;
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return p.a.Demo.internal_static_p_a_UserInfo_descriptor;
        }

        public static p.a.Demo.UserInfo parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.UserInfo parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.UserInfo parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.UserInfo parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.UserInfo parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.UserInfo parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.UserInfo parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Demo.UserInfo parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Demo.UserInfo parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static p.a.Demo.UserInfo parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Demo.UserInfo parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Demo.UserInfo parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(p.a.Demo.UserInfo prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static p.a.Demo.UserInfo getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<UserInfo> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new UserInfo();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return p.a.Demo.internal_static_p_a_UserInfo_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            p.a.Demo.UserInfo.class, p.a.Demo.UserInfo.Builder.class);
        }

        /**
         * <code>int64 acctID = 1;</code>
         *
         * @return The acctID.
         */
        @java.lang.Override
        public long getAcctID() {
            return acctID_;
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <code>string name = 2;</code>
         *
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>.p.a.UserStatus status = 3;</code>
         *
         * @return The enum numeric value on the wire for status.
         */
        @java.lang.Override
        public int getStatusValue() {
            return status_;
        }

        /**
         * <code>.p.a.UserStatus status = 3;</code>
         *
         * @return The status.
         */
        @java.lang.Override
        public p.a.Demo.UserStatus getStatus() {
            @SuppressWarnings("deprecation")
            p.a.Demo.UserStatus result = p.a.Demo.UserStatus.valueOf(status_);
            return result == null ? p.a.Demo.UserStatus.UNRECOGNIZED : result;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (acctID_ != 0L) {
                output.writeInt64(1, acctID_);
            }
            if (!getNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            if (status_ != p.a.Demo.UserStatus.OFFLINE.getNumber()) {
                output.writeEnum(3, status_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (acctID_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, acctID_);
            }
            if (!getNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            if (status_ != p.a.Demo.UserStatus.OFFLINE.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(3, status_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof p.a.Demo.UserInfo)) {
                return super.equals(obj);
            }
            p.a.Demo.UserInfo other = (p.a.Demo.UserInfo) obj;

            if (getAcctID()
                    != other.getAcctID()) return false;
            if (!getName()
                    .equals(other.getName())) return false;
            if (status_ != other.status_) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ACCTID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getAcctID());
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (37 * hash) + STATUS_FIELD_NUMBER;
            hash = (53 * hash) + status_;
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<UserInfo> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public p.a.Demo.UserInfo getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code p.a.UserInfo}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:p.a.UserInfo)
                p.a.Demo.UserInfoOrBuilder {
            private long acctID_;
            private java.lang.Object name_ = "";
            private int status_ = 0;

            // Construct using p.a.Demo.UserInfo.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return p.a.Demo.internal_static_p_a_UserInfo_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return p.a.Demo.internal_static_p_a_UserInfo_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                p.a.Demo.UserInfo.class, p.a.Demo.UserInfo.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                acctID_ = 0L;

                name_ = "";

                status_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return p.a.Demo.internal_static_p_a_UserInfo_descriptor;
            }

            @java.lang.Override
            public p.a.Demo.UserInfo getDefaultInstanceForType() {
                return p.a.Demo.UserInfo.getDefaultInstance();
            }

            @java.lang.Override
            public p.a.Demo.UserInfo build() {
                p.a.Demo.UserInfo result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public p.a.Demo.UserInfo buildPartial() {
                p.a.Demo.UserInfo result = new p.a.Demo.UserInfo(this);
                result.acctID_ = acctID_;
                result.name_ = name_;
                result.status_ = status_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof p.a.Demo.UserInfo) {
                    return mergeFrom((p.a.Demo.UserInfo) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(p.a.Demo.UserInfo other) {
                if (other == p.a.Demo.UserInfo.getDefaultInstance()) return this;
                if (other.getAcctID() != 0L) {
                    setAcctID(other.getAcctID());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    onChanged();
                }
                if (other.status_ != 0) {
                    setStatusValue(other.getStatusValue());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                p.a.Demo.UserInfo parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (p.a.Demo.UserInfo) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int64 acctID = 1;</code>
             *
             * @return The acctID.
             */
            @java.lang.Override
            public long getAcctID() {
                return acctID_;
            }

            /**
             * <code>int64 acctID = 1;</code>
             *
             * @param value The acctID to set.
             * @return This builder for chaining.
             */
            public Builder setAcctID(long value) {

                acctID_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 acctID = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAcctID() {

                acctID_ = 0L;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             *
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             *
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             *
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string name = 2;</code>
             *
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string name = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearName() {

                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.UserStatus status = 3;</code>
             *
             * @return The enum numeric value on the wire for status.
             */
            @java.lang.Override
            public int getStatusValue() {
                return status_;
            }

            /**
             * <code>.p.a.UserStatus status = 3;</code>
             *
             * @param value The enum numeric value on the wire for status to set.
             * @return This builder for chaining.
             */
            public Builder setStatusValue(int value) {

                status_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.UserStatus status = 3;</code>
             *
             * @return The status.
             */
            @java.lang.Override
            public p.a.Demo.UserStatus getStatus() {
                @SuppressWarnings("deprecation")
                p.a.Demo.UserStatus result = p.a.Demo.UserStatus.valueOf(status_);
                return result == null ? p.a.Demo.UserStatus.UNRECOGNIZED : result;
            }

            /**
             * <code>.p.a.UserStatus status = 3;</code>
             *
             * @param value The status to set.
             * @return This builder for chaining.
             */
            public Builder setStatus(p.a.Demo.UserStatus value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                status_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.UserStatus status = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearStatus() {

                status_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:p.a.UserInfo)
        }

    }

    /**
     * Protobuf type {@code p.a.LogonRespMessage}
     */
    public static final class LogonRespMessage extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:p.a.LogonRespMessage)
            LogonRespMessageOrBuilder {
        public static final int LOGONRESULT_FIELD_NUMBER = 1;
        public static final int USERINFO_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:p.a.LogonRespMessage)
        private static final p.a.Demo.LogonRespMessage DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<LogonRespMessage>
                PARSER = new com.google.protobuf.AbstractParser<LogonRespMessage>() {
            @java.lang.Override
            public LogonRespMessage parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new LogonRespMessage(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new p.a.Demo.LogonRespMessage();
        }

        private int logonResult_;
        private p.a.Demo.UserInfo userInfo_;
        private byte memoizedIsInitialized = -1;

        // Use LogonRespMessage.newBuilder() to construct.
        private LogonRespMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private LogonRespMessage() {
            logonResult_ = 0;
        }

        private LogonRespMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            int rawValue = input.readEnum();

                            logonResult_ = rawValue;
                            break;
                        }
                        case 18: {
                            p.a.Demo.UserInfo.Builder subBuilder = null;
                            if (userInfo_ != null) {
                                subBuilder = userInfo_.toBuilder();
                            }
                            userInfo_ = input.readMessage(p.a.Demo.UserInfo.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(userInfo_);
                                userInfo_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return p.a.Demo.internal_static_p_a_LogonRespMessage_descriptor;
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Demo.LogonRespMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static p.a.Demo.LogonRespMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Demo.LogonRespMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(p.a.Demo.LogonRespMessage prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static p.a.Demo.LogonRespMessage getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<LogonRespMessage> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new LogonRespMessage();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return p.a.Demo.internal_static_p_a_LogonRespMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            p.a.Demo.LogonRespMessage.class, p.a.Demo.LogonRespMessage.Builder.class);
        }

        /**
         * <code>.p.a.LoginResult logonResult = 1;</code>
         *
         * @return The enum numeric value on the wire for logonResult.
         */
        @java.lang.Override
        public int getLogonResultValue() {
            return logonResult_;
        }

        /**
         * <code>.p.a.LoginResult logonResult = 1;</code>
         *
         * @return The logonResult.
         */
        @java.lang.Override
        public p.a.Demo.LoginResult getLogonResult() {
            @SuppressWarnings("deprecation")
            p.a.Demo.LoginResult result = p.a.Demo.LoginResult.valueOf(logonResult_);
            return result == null ? p.a.Demo.LoginResult.UNRECOGNIZED : result;
        }

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         *
         * @return Whether the userInfo field is set.
         */
        @java.lang.Override
        public boolean hasUserInfo() {
            return userInfo_ != null;
        }

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         *
         * @return The userInfo.
         */
        @java.lang.Override
        public p.a.Demo.UserInfo getUserInfo() {
            return userInfo_ == null ? p.a.Demo.UserInfo.getDefaultInstance() : userInfo_;
        }

        /**
         * <pre>
         * 这里嵌套了UserInfo消息。
         * </pre>
         *
         * <code>.p.a.UserInfo userInfo = 2;</code>
         */
        @java.lang.Override
        public p.a.Demo.UserInfoOrBuilder getUserInfoOrBuilder() {
            return getUserInfo();
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (logonResult_ != p.a.Demo.LoginResult.LOGON_RESULT_SUCCESS.getNumber()) {
                output.writeEnum(1, logonResult_);
            }
            if (userInfo_ != null) {
                output.writeMessage(2, getUserInfo());
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (logonResult_ != p.a.Demo.LoginResult.LOGON_RESULT_SUCCESS.getNumber()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, logonResult_);
            }
            if (userInfo_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getUserInfo());
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof p.a.Demo.LogonRespMessage)) {
                return super.equals(obj);
            }
            p.a.Demo.LogonRespMessage other = (p.a.Demo.LogonRespMessage) obj;

            if (logonResult_ != other.logonResult_) return false;
            if (hasUserInfo() != other.hasUserInfo()) return false;
            if (hasUserInfo()) {
                if (!getUserInfo()
                        .equals(other.getUserInfo())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + LOGONRESULT_FIELD_NUMBER;
            hash = (53 * hash) + logonResult_;
            if (hasUserInfo()) {
                hash = (37 * hash) + USERINFO_FIELD_NUMBER;
                hash = (53 * hash) + getUserInfo().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<LogonRespMessage> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public p.a.Demo.LogonRespMessage getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code p.a.LogonRespMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:p.a.LogonRespMessage)
                p.a.Demo.LogonRespMessageOrBuilder {
            private int logonResult_ = 0;
            private p.a.Demo.UserInfo userInfo_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    p.a.Demo.UserInfo, p.a.Demo.UserInfo.Builder, p.a.Demo.UserInfoOrBuilder> userInfoBuilder_;

            // Construct using p.a.Demo.LogonRespMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return p.a.Demo.internal_static_p_a_LogonRespMessage_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return p.a.Demo.internal_static_p_a_LogonRespMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                p.a.Demo.LogonRespMessage.class, p.a.Demo.LogonRespMessage.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                logonResult_ = 0;

                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return p.a.Demo.internal_static_p_a_LogonRespMessage_descriptor;
            }

            @java.lang.Override
            public p.a.Demo.LogonRespMessage getDefaultInstanceForType() {
                return p.a.Demo.LogonRespMessage.getDefaultInstance();
            }

            @java.lang.Override
            public p.a.Demo.LogonRespMessage build() {
                p.a.Demo.LogonRespMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public p.a.Demo.LogonRespMessage buildPartial() {
                p.a.Demo.LogonRespMessage result = new p.a.Demo.LogonRespMessage(this);
                result.logonResult_ = logonResult_;
                if (userInfoBuilder_ == null) {
                    result.userInfo_ = userInfo_;
                } else {
                    result.userInfo_ = userInfoBuilder_.build();
                }
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof p.a.Demo.LogonRespMessage) {
                    return mergeFrom((p.a.Demo.LogonRespMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(p.a.Demo.LogonRespMessage other) {
                if (other == p.a.Demo.LogonRespMessage.getDefaultInstance()) return this;
                if (other.logonResult_ != 0) {
                    setLogonResultValue(other.getLogonResultValue());
                }
                if (other.hasUserInfo()) {
                    mergeUserInfo(other.getUserInfo());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                p.a.Demo.LogonRespMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (p.a.Demo.LogonRespMessage) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>.p.a.LoginResult logonResult = 1;</code>
             *
             * @return The enum numeric value on the wire for logonResult.
             */
            @java.lang.Override
            public int getLogonResultValue() {
                return logonResult_;
            }

            /**
             * <code>.p.a.LoginResult logonResult = 1;</code>
             *
             * @param value The enum numeric value on the wire for logonResult to set.
             * @return This builder for chaining.
             */
            public Builder setLogonResultValue(int value) {

                logonResult_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.LoginResult logonResult = 1;</code>
             *
             * @return The logonResult.
             */
            @java.lang.Override
            public p.a.Demo.LoginResult getLogonResult() {
                @SuppressWarnings("deprecation")
                p.a.Demo.LoginResult result = p.a.Demo.LoginResult.valueOf(logonResult_);
                return result == null ? p.a.Demo.LoginResult.UNRECOGNIZED : result;
            }

            /**
             * <code>.p.a.LoginResult logonResult = 1;</code>
             *
             * @param value The logonResult to set.
             * @return This builder for chaining.
             */
            public Builder setLogonResult(p.a.Demo.LoginResult value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                logonResult_ = value.getNumber();
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.LoginResult logonResult = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearLogonResult() {

                logonResult_ = 0;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             *
             * @return Whether the userInfo field is set.
             */
            public boolean hasUserInfo() {
                return userInfoBuilder_ != null || userInfo_ != null;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             *
             * @return The userInfo.
             */
            public p.a.Demo.UserInfo getUserInfo() {
                if (userInfoBuilder_ == null) {
                    return userInfo_ == null ? p.a.Demo.UserInfo.getDefaultInstance() : userInfo_;
                } else {
                    return userInfoBuilder_.getMessage();
                }
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public Builder setUserInfo(p.a.Demo.UserInfo value) {
                if (userInfoBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    userInfo_ = value;
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public Builder setUserInfo(
                    p.a.Demo.UserInfo.Builder builderForValue) {
                if (userInfoBuilder_ == null) {
                    userInfo_ = builderForValue.build();
                    onChanged();
                } else {
                    userInfoBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public Builder mergeUserInfo(p.a.Demo.UserInfo value) {
                if (userInfoBuilder_ == null) {
                    if (userInfo_ != null) {
                        userInfo_ =
                                p.a.Demo.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
                    } else {
                        userInfo_ = value;
                    }
                    onChanged();
                } else {
                    userInfoBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public Builder clearUserInfo() {
                if (userInfoBuilder_ == null) {
                    userInfo_ = null;
                    onChanged();
                } else {
                    userInfo_ = null;
                    userInfoBuilder_ = null;
                }

                return this;
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public p.a.Demo.UserInfo.Builder getUserInfoBuilder() {

                onChanged();
                return getUserInfoFieldBuilder().getBuilder();
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            public p.a.Demo.UserInfoOrBuilder getUserInfoOrBuilder() {
                if (userInfoBuilder_ != null) {
                    return userInfoBuilder_.getMessageOrBuilder();
                } else {
                    return userInfo_ == null ?
                            p.a.Demo.UserInfo.getDefaultInstance() : userInfo_;
                }
            }

            /**
             * <pre>
             * 这里嵌套了UserInfo消息。
             * </pre>
             *
             * <code>.p.a.UserInfo userInfo = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    p.a.Demo.UserInfo, p.a.Demo.UserInfo.Builder, p.a.Demo.UserInfoOrBuilder>
            getUserInfoFieldBuilder() {
                if (userInfoBuilder_ == null) {
                    userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            p.a.Demo.UserInfo, p.a.Demo.UserInfo.Builder, p.a.Demo.UserInfoOrBuilder>(
                            getUserInfo(),
                            getParentForChildren(),
                            isClean());
                    userInfo_ = null;
                }
                return userInfoBuilder_;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:p.a.LogonRespMessage)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
