// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Test.proto

package p.a;

public final class Test {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_p_a_Person_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_p_a_Person_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nTest.proto\022\003p.a\032\007A.proto\"9\n\006Person\022\013\n\003" +
                        "age\030\001 \001(\005\022\025\n\003car\030\002 \001(\0132\010.p.a.Car\022\013\n\003ids\030" +
                        "\003 \003(\005b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                p.a.A.getDescriptor(),
                        });
        internal_static_p_a_Person_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_p_a_Person_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_p_a_Person_descriptor,
                new java.lang.String[]{"Age", "Car", "Ids",});
        p.a.A.getDescriptor();
    }

    private Test() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface PersonOrBuilder extends
            // @@protoc_insertion_point(interface_extends:p.a.Person)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int32 age = 1;</code>
         *
         * @return The age.
         */
        int getAge();

        /**
         * <code>.p.a.Car car = 2;</code>
         *
         * @return Whether the car field is set.
         */
        boolean hasCar();

        /**
         * <code>.p.a.Car car = 2;</code>
         *
         * @return The car.
         */
        p.a.A.Car getCar();

        /**
         * <code>.p.a.Car car = 2;</code>
         */
        p.a.A.CarOrBuilder getCarOrBuilder();

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @return A list containing the ids.
         */
        java.util.List<java.lang.Integer> getIdsList();

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @return The count of ids.
         */
        int getIdsCount();

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The ids at the given index.
         */
        int getIds(int index);
    }

    /**
     * Protobuf type {@code p.a.Person}
     */
    public static final class Person extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:p.a.Person)
            PersonOrBuilder {
        public static final int AGE_FIELD_NUMBER = 1;
        public static final int CAR_FIELD_NUMBER = 2;
        public static final int IDS_FIELD_NUMBER = 3;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:p.a.Person)
        private static final p.a.Test.Person DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<Person>
                PARSER = new com.google.protobuf.AbstractParser<Person>() {
            @java.lang.Override
            public Person parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Person(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new p.a.Test.Person();
        }

        private int age_;
        private p.a.A.Car car_;
        private com.google.protobuf.Internal.IntList ids_;
        private int idsMemoizedSerializedSize = -1;
        private byte memoizedIsInitialized = -1;

        // Use Person.newBuilder() to construct.
        private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Person() {
            ids_ = emptyIntList();
        }

        private Person(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            age_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            p.a.A.Car.Builder subBuilder = null;
                            if (car_ != null) {
                                subBuilder = car_.toBuilder();
                            }
                            car_ = input.readMessage(p.a.A.Car.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(car_);
                                car_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 24: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                ids_ = newIntList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            ids_.addInt(input.readInt32());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                                ids_ = newIntList();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            while (input.getBytesUntilLimit() > 0) {
                                ids_.addInt(input.readInt32());
                            }
                            input.popLimit(limit);
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) != 0)) {
                    ids_.makeImmutable(); // C
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return p.a.Test.internal_static_p_a_Person_descriptor;
        }

        public static p.a.Test.Person parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Test.Person parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Test.Person parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Test.Person parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Test.Person parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static p.a.Test.Person parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static p.a.Test.Person parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Test.Person parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Test.Person parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static p.a.Test.Person parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static p.a.Test.Person parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static p.a.Test.Person parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(p.a.Test.Person prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static p.a.Test.Person getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<Person> parser() {
            return PARSER;
        }

        @java.lang.Override
        @SuppressWarnings({"unused"})
        protected java.lang.Object newInstance(
                UnusedPrivateParameter unused) {
            return new Person();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return p.a.Test.internal_static_p_a_Person_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            p.a.Test.Person.class, p.a.Test.Person.Builder.class);
        }

        /**
         * <code>int32 age = 1;</code>
         *
         * @return The age.
         */
        @java.lang.Override
        public int getAge() {
            return age_;
        }

        /**
         * <code>.p.a.Car car = 2;</code>
         *
         * @return Whether the car field is set.
         */
        @java.lang.Override
        public boolean hasCar() {
            return car_ != null;
        }

        /**
         * <code>.p.a.Car car = 2;</code>
         *
         * @return The car.
         */
        @java.lang.Override
        public p.a.A.Car getCar() {
            return car_ == null ? p.a.A.Car.getDefaultInstance() : car_;
        }

        /**
         * <code>.p.a.Car car = 2;</code>
         */
        @java.lang.Override
        public p.a.A.CarOrBuilder getCarOrBuilder() {
            return getCar();
        }

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @return A list containing the ids.
         */
        @java.lang.Override
        public java.util.List<java.lang.Integer>
        getIdsList() {
            return ids_;
        }

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @return The count of ids.
         */
        public int getIdsCount() {
            return ids_.size();
        }

        /**
         * <code>repeated int32 ids = 3;</code>
         *
         * @param index The index of the element to return.
         * @return The ids at the given index.
         */
        public int getIds(int index) {
            return ids_.getInt(index);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (age_ != 0) {
                output.writeInt32(1, age_);
            }
            if (car_ != null) {
                output.writeMessage(2, getCar());
            }
            if (getIdsList().size() > 0) {
                output.writeUInt32NoTag(26);
                output.writeUInt32NoTag(idsMemoizedSerializedSize);
            }
            for (int i = 0; i < ids_.size(); i++) {
                output.writeInt32NoTag(ids_.getInt(i));
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (age_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, age_);
            }
            if (car_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, getCar());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < ids_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(ids_.getInt(i));
                }
                size += dataSize;
                if (!getIdsList().isEmpty()) {
                    size += 1;
                    size += com.google.protobuf.CodedOutputStream
                            .computeInt32SizeNoTag(dataSize);
                }
                idsMemoizedSerializedSize = dataSize;
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof p.a.Test.Person)) {
                return super.equals(obj);
            }
            p.a.Test.Person other = (p.a.Test.Person) obj;

            if (getAge()
                    != other.getAge()) return false;
            if (hasCar() != other.hasCar()) return false;
            if (hasCar()) {
                if (!getCar()
                        .equals(other.getCar())) return false;
            }
            if (!getIdsList()
                    .equals(other.getIdsList())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + AGE_FIELD_NUMBER;
            hash = (53 * hash) + getAge();
            if (hasCar()) {
                hash = (37 * hash) + CAR_FIELD_NUMBER;
                hash = (53 * hash) + getCar().hashCode();
            }
            if (getIdsCount() > 0) {
                hash = (37 * hash) + IDS_FIELD_NUMBER;
                hash = (53 * hash) + getIdsList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Person> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public p.a.Test.Person getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code p.a.Person}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:p.a.Person)
                p.a.Test.PersonOrBuilder {
            private int bitField0_;
            private int age_;
            private p.a.A.Car car_;
            private com.google.protobuf.SingleFieldBuilderV3<
                    p.a.A.Car, p.a.A.Car.Builder, p.a.A.CarOrBuilder> carBuilder_;
            private com.google.protobuf.Internal.IntList ids_ = emptyIntList();

            // Construct using p.a.Test.Person.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return p.a.Test.internal_static_p_a_Person_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return p.a.Test.internal_static_p_a_Person_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                p.a.Test.Person.class, p.a.Test.Person.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                age_ = 0;

                if (carBuilder_ == null) {
                    car_ = null;
                } else {
                    car_ = null;
                    carBuilder_ = null;
                }
                ids_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return p.a.Test.internal_static_p_a_Person_descriptor;
            }

            @java.lang.Override
            public p.a.Test.Person getDefaultInstanceForType() {
                return p.a.Test.Person.getDefaultInstance();
            }

            @java.lang.Override
            public p.a.Test.Person build() {
                p.a.Test.Person result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public p.a.Test.Person buildPartial() {
                p.a.Test.Person result = new p.a.Test.Person(this);
                int from_bitField0_ = bitField0_;
                result.age_ = age_;
                if (carBuilder_ == null) {
                    result.car_ = car_;
                } else {
                    result.car_ = carBuilder_.build();
                }
                if (((bitField0_ & 0x00000001) != 0)) {
                    ids_.makeImmutable();
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.ids_ = ids_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof p.a.Test.Person) {
                    return mergeFrom((p.a.Test.Person) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(p.a.Test.Person other) {
                if (other == p.a.Test.Person.getDefaultInstance()) return this;
                if (other.getAge() != 0) {
                    setAge(other.getAge());
                }
                if (other.hasCar()) {
                    mergeCar(other.getCar());
                }
                if (!other.ids_.isEmpty()) {
                    if (ids_.isEmpty()) {
                        ids_ = other.ids_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureIdsIsMutable();
                        ids_.addAll(other.ids_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                p.a.Test.Person parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (p.a.Test.Person) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>int32 age = 1;</code>
             *
             * @return The age.
             */
            @java.lang.Override
            public int getAge() {
                return age_;
            }

            /**
             * <code>int32 age = 1;</code>
             *
             * @param value The age to set.
             * @return This builder for chaining.
             */
            public Builder setAge(int value) {

                age_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 age = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearAge() {

                age_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             *
             * @return Whether the car field is set.
             */
            public boolean hasCar() {
                return carBuilder_ != null || car_ != null;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             *
             * @return The car.
             */
            public p.a.A.Car getCar() {
                if (carBuilder_ == null) {
                    return car_ == null ? p.a.A.Car.getDefaultInstance() : car_;
                } else {
                    return carBuilder_.getMessage();
                }
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public Builder setCar(p.a.A.Car value) {
                if (carBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    car_ = value;
                    onChanged();
                } else {
                    carBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public Builder setCar(
                    p.a.A.Car.Builder builderForValue) {
                if (carBuilder_ == null) {
                    car_ = builderForValue.build();
                    onChanged();
                } else {
                    carBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public Builder mergeCar(p.a.A.Car value) {
                if (carBuilder_ == null) {
                    if (car_ != null) {
                        car_ =
                                p.a.A.Car.newBuilder(car_).mergeFrom(value).buildPartial();
                    } else {
                        car_ = value;
                    }
                    onChanged();
                } else {
                    carBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public Builder clearCar() {
                if (carBuilder_ == null) {
                    car_ = null;
                    onChanged();
                } else {
                    car_ = null;
                    carBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public p.a.A.Car.Builder getCarBuilder() {

                onChanged();
                return getCarFieldBuilder().getBuilder();
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            public p.a.A.CarOrBuilder getCarOrBuilder() {
                if (carBuilder_ != null) {
                    return carBuilder_.getMessageOrBuilder();
                } else {
                    return car_ == null ?
                            p.a.A.Car.getDefaultInstance() : car_;
                }
            }

            /**
             * <code>.p.a.Car car = 2;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    p.a.A.Car, p.a.A.Car.Builder, p.a.A.CarOrBuilder>
            getCarFieldBuilder() {
                if (carBuilder_ == null) {
                    carBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            p.a.A.Car, p.a.A.Car.Builder, p.a.A.CarOrBuilder>(
                            getCar(),
                            getParentForChildren(),
                            isClean());
                    car_ = null;
                }
                return carBuilder_;
            }

            private void ensureIdsIsMutable() {
                if (!((bitField0_ & 0x00000001) != 0)) {
                    ids_ = mutableCopy(ids_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @return A list containing the ids.
             */
            public java.util.List<java.lang.Integer>
            getIdsList() {
                return ((bitField0_ & 0x00000001) != 0) ?
                        java.util.Collections.unmodifiableList(ids_) : ids_;
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @return The count of ids.
             */
            public int getIdsCount() {
                return ids_.size();
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @param index The index of the element to return.
             * @return The ids at the given index.
             */
            public int getIds(int index) {
                return ids_.getInt(index);
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @param index The index to set the value at.
             * @param value The ids to set.
             * @return This builder for chaining.
             */
            public Builder setIds(
                    int index, int value) {
                ensureIdsIsMutable();
                ids_.setInt(index, value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @param value The ids to add.
             * @return This builder for chaining.
             */
            public Builder addIds(int value) {
                ensureIdsIsMutable();
                ids_.addInt(value);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @param values The ids to add.
             * @return This builder for chaining.
             */
            public Builder addAllIds(
                    java.lang.Iterable<? extends java.lang.Integer> values) {
                ensureIdsIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, ids_);
                onChanged();
                return this;
            }

            /**
             * <code>repeated int32 ids = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearIds() {
                ids_ = emptyIntList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:p.a.Person)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
