// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: A.proto

package p.a;

public final class A {
  private A() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(p.a.A.aaa);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code p.a.CarType}
   */
  public enum CarType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BENCHI = 0;</code>
     */
    BENCHI(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BENCHI = 0;</code>
     */
    public static final int BENCHI_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CarType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CarType forNumber(int value) {
      switch (value) {
        case 0: return BENCHI;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CarType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CarType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CarType>() {
            public CarType findValueByNumber(int number) {
              return CarType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return p.a.A.getDescriptor().getEnumTypes().get(0);
    }

    private static final CarType[] VALUES = values();

    public static CarType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CarType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:p.a.CarType)
  }

  public interface CarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:p.a.Car)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *hello
     * </pre>
     *
     * <code>.p.a.CarType type = 2 [deprecated = true];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Deprecated int getTypeValue();
    /**
     * <pre>
     *hello
     * </pre>
     *
     * <code>.p.a.CarType type = 2 [deprecated = true];</code>
     * @return The type.
     */
    @java.lang.Deprecated p.a.A.CarType getType();

    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     * @return Whether the param field is set.
     */
    boolean hasParam();
    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     * @return The param.
     */
    com.google.protobuf.Any getParam();
    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     */
    com.google.protobuf.AnyOrBuilder getParamOrBuilder();
  }
  /**
   * Protobuf type {@code p.a.Car}
   */
  public static final class Car extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:p.a.Car)
      CarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Car.newBuilder() to construct.
    private Car(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Car() {
      name_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Car();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Car(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (param_ != null) {
                subBuilder = param_.toBuilder();
              }
              param_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(param_);
                param_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return p.a.A.internal_static_p_a_Car_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return p.a.A.internal_static_p_a_Car_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              p.a.A.Car.class, p.a.A.Car.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     *hello
     * </pre>
     *
     * <code>.p.a.CarType type = 2 [deprecated = true];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override @java.lang.Deprecated public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *hello
     * </pre>
     *
     * <code>.p.a.CarType type = 2 [deprecated = true];</code>
     * @return The type.
     */
    @java.lang.Override @java.lang.Deprecated public p.a.A.CarType getType() {
      @SuppressWarnings("deprecation")
      p.a.A.CarType result = p.a.A.CarType.valueOf(type_);
      return result == null ? p.a.A.CarType.UNRECOGNIZED : result;
    }

    public static final int PARAM_FIELD_NUMBER = 3;
    private com.google.protobuf.Any param_;
    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     * @return Whether the param field is set.
     */
    @java.lang.Override
    public boolean hasParam() {
      return param_ != null;
    }
    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     * @return The param.
     */
    @java.lang.Override
    public com.google.protobuf.Any getParam() {
      return param_ == null ? com.google.protobuf.Any.getDefaultInstance() : param_;
    }
    /**
     * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getParamOrBuilder() {
      return getParam();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (type_ != p.a.A.CarType.BENCHI.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (param_ != null) {
        output.writeMessage(3, getParam());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (type_ != p.a.A.CarType.BENCHI.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (param_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getParam());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof p.a.A.Car)) {
        return super.equals(obj);
      }
      p.a.A.Car other = (p.a.A.Car) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (type_ != other.type_) return false;
      if (hasParam() != other.hasParam()) return false;
      if (hasParam()) {
        if (!getParam()
            .equals(other.getParam())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasParam()) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getParam().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static p.a.A.Car parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static p.a.A.Car parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static p.a.A.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static p.a.A.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static p.a.A.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static p.a.A.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static p.a.A.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static p.a.A.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static p.a.A.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static p.a.A.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static p.a.A.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static p.a.A.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(p.a.A.Car prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code p.a.Car}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:p.a.Car)
        p.a.A.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return p.a.A.internal_static_p_a_Car_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return p.a.A.internal_static_p_a_Car_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                p.a.A.Car.class, p.a.A.Car.Builder.class);
      }

      // Construct using p.a.A.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        type_ = 0;

        if (paramBuilder_ == null) {
          param_ = null;
        } else {
          param_ = null;
          paramBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return p.a.A.internal_static_p_a_Car_descriptor;
      }

      @java.lang.Override
      public p.a.A.Car getDefaultInstanceForType() {
        return p.a.A.Car.getDefaultInstance();
      }

      @java.lang.Override
      public p.a.A.Car build() {
        p.a.A.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public p.a.A.Car buildPartial() {
        p.a.A.Car result = new p.a.A.Car(this);
        result.name_ = name_;
        result.type_ = type_;
        if (paramBuilder_ == null) {
          result.param_ = param_;
        } else {
          result.param_ = paramBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof p.a.A.Car) {
          return mergeFrom((p.a.A.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(p.a.A.Car other) {
        if (other == p.a.A.Car.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasParam()) {
          mergeParam(other.getParam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        p.a.A.Car parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (p.a.A.Car) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *hello
       * </pre>
       *
       * <code>.p.a.CarType type = 2 [deprecated = true];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override @java.lang.Deprecated public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *hello
       * </pre>
       *
       * <code>.p.a.CarType type = 2 [deprecated = true];</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *hello
       * </pre>
       *
       * <code>.p.a.CarType type = 2 [deprecated = true];</code>
       * @return The type.
       */
      @java.lang.Override
      @java.lang.Deprecated public p.a.A.CarType getType() {
        @SuppressWarnings("deprecation")
        p.a.A.CarType result = p.a.A.CarType.valueOf(type_);
        return result == null ? p.a.A.CarType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *hello
       * </pre>
       *
       * <code>.p.a.CarType type = 2 [deprecated = true];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder setType(p.a.A.CarType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *hello
       * </pre>
       *
       * <code>.p.a.CarType type = 2 [deprecated = true];</code>
       * @return This builder for chaining.
       */
      @java.lang.Deprecated public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any param_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> paramBuilder_;
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       * @return Whether the param field is set.
       */
      public boolean hasParam() {
        return paramBuilder_ != null || param_ != null;
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       * @return The param.
       */
      public com.google.protobuf.Any getParam() {
        if (paramBuilder_ == null) {
          return param_ == null ? com.google.protobuf.Any.getDefaultInstance() : param_;
        } else {
          return paramBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public Builder setParam(com.google.protobuf.Any value) {
        if (paramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          param_ = value;
          onChanged();
        } else {
          paramBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public Builder setParam(
          com.google.protobuf.Any.Builder builderForValue) {
        if (paramBuilder_ == null) {
          param_ = builderForValue.build();
          onChanged();
        } else {
          paramBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public Builder mergeParam(com.google.protobuf.Any value) {
        if (paramBuilder_ == null) {
          if (param_ != null) {
            param_ =
              com.google.protobuf.Any.newBuilder(param_).mergeFrom(value).buildPartial();
          } else {
            param_ = value;
          }
          onChanged();
        } else {
          paramBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public Builder clearParam() {
        if (paramBuilder_ == null) {
          param_ = null;
          onChanged();
        } else {
          param_ = null;
          paramBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public com.google.protobuf.Any.Builder getParamBuilder() {
        
        onChanged();
        return getParamFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      public com.google.protobuf.AnyOrBuilder getParamOrBuilder() {
        if (paramBuilder_ != null) {
          return paramBuilder_.getMessageOrBuilder();
        } else {
          return param_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : param_;
        }
      }
      /**
       * <code>.google.protobuf.Any param = 3 [(.p.a.aaa) = "hello"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getParamFieldBuilder() {
        if (paramBuilder_ == null) {
          paramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getParam(),
                  getParentForChildren(),
                  isClean());
          param_ = null;
        }
        return paramBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:p.a.Car)
    }

    // @@protoc_insertion_point(class_scope:p.a.Car)
    private static final p.a.A.Car DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new p.a.A.Car();
    }

    public static p.a.A.Car getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Car>
        PARSER = new com.google.protobuf.AbstractParser<Car>() {
      @java.lang.Override
      public Car parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Car(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Car> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Car> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public p.a.A.Car getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int AAA_FIELD_NUMBER = 10001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      java.lang.String> aaa = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_p_a_Car_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_p_a_Car_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\007A.proto\022\003p.a\032\031google/protobuf/any.prot" +
      "o\032 google/protobuf/descriptor.proto\"c\n\003C" +
      "ar\022\014\n\004name\030\001 \001(\t\022\036\n\004type\030\002 \001(\0162\014.p.a.Car" +
      "TypeB\002\030\001\022.\n\005param\030\003 \001(\0132\024.google.protobu" +
      "f.AnyB\t\212\361\004\005hello*\025\n\007CarType\022\n\n\006BENCHI\020\000:" +
      "+\n\003aaa\022\035.google.protobuf.FieldOptions\030\221N" +
      " \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_p_a_Car_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_p_a_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_p_a_Car_descriptor,
        new java.lang.String[] { "Name", "Type", "Param", });
    aaa.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(p.a.A.aaa);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
