package com.github.study.guava;

import cn.dongshi.framework.toolkit.StringKit;
import com.caucho.hessian.io.Hessian2Output;
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.io.Output;
import com.google.protobuf.DescriptorProtos;
import com.google.protobuf.Descriptors;
import com.google.protobuf.InvalidProtocolBufferException;
import io.protostuff.LinkedBuffer;
import io.protostuff.ProtobufIOUtil;
import io.protostuff.Schema;
import io.protostuff.runtime.RuntimeSchema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.msgpack.MessagePack;
import org.msgpack.annotation.Message;
import org.objenesis.strategy.StdInstantiatorStrategy;
import p.a.Demo;

import java.io.*;

/**
 * CreatedDate: 2021/2/24
 * Author: songjialin
 */
public class ProtoTest {
    public static void main(String[] args) throws IOException {
        Person person = new Person("mushan", 20);
        test4(person);
    }

    private static void test5(Person person) {
        Kryo kryo = new Kryo();
        kryo.setReferences(true); //默认值就是 true，添加此行的目的是为了提醒维护者，不要改变这个配置
        //不强制要求注册类（注册行为无法保证多个 JVM 内同一个类的注册编号相同；而且业务系统中大量的 Class 也难以一一注册）
        kryo.setRegistrationRequired(false); //默认值就是 false，添加此行的目的是为了提醒维护者，不要改变这个配置
        ((Kryo.DefaultInstantiatorStrategy) kryo.getInstantiatorStrategy())
                .setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());
        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        Output output = new Output(byteArrayOutputStream);
        kryo.writeClassAndObject(output, person);
        output.flush();
        byte[] bytes = byteArrayOutputStream.toByteArray();
        System.out.println(StringKit.newStringUtf8(bytes));
    }

    private static void test4(Person p) throws IOException {
        MessagePack messagePack = new MessagePack();
        byte[] bs = messagePack.write(p);
        System.out.println(StringKit.newStringUtf8(bs));
        Person serializableUserinfo = messagePack.read(bs, Person.class);
        System.out.println(serializableUserinfo);
    }

    private static void test3(Person p) throws IOException {
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        Hessian2Output output = new Hessian2Output(os);
        output.writeObject(p);
        output.flush();
        byte[] bytes = os.toByteArray();
        System.out.println(StringKit.newStringUtf8(bytes));
    }

    private static void test2(Person p) {
        LinkedBuffer buffer = LinkedBuffer.allocate();
        Schema<Person> schema = RuntimeSchema.getSchema(Person.class);
        Schema<Person2> schema2 = RuntimeSchema.getSchema(Person2.class);
        byte[] protobuf = ProtobufIOUtil.toByteArray(p, schema, buffer);
        System.out.println(StringKit.newStringUtf8(protobuf));
        Person2 person2 = schema2.newMessage();
        ProtobufIOUtil.mergeFrom(protobuf, person2, schema2);
        System.out.println(person2);
    }

    private static void test1() {
        System.out.println("==================This is nested message.================");
        Demo.LogonRespMessage.Builder logonRespBuilder = Demo.LogonRespMessage.newBuilder();
        logonRespBuilder.setLogonResult(Demo.LoginResult.LOGON_RESULT_SUCCESS);
        Demo.UserInfo.Builder userInfo = Demo.UserInfo.newBuilder();
        userInfo.setAcctID(200);
        userInfo.setName("Tester");
        userInfo.setStatus(Demo.UserStatus.OFFLINE);
        //这里也可以直接传递userInfo对象作为参数。因为LogonRespBuilder类提供了setUserInfo的方法重载。
        logonRespBuilder.setUserInfo(userInfo.build());
        Demo.LogonRespMessage logonResp = logonRespBuilder.build();
        int length = logonResp.getSerializedSize();
        System.out.println("The result length is " + length);
        byte[] buf = logonResp.toByteArray();
        Descriptors.Descriptor descriptor = Demo.LogonRespMessage.getDescriptor();
        Descriptors.Descriptor descriptorForType = logonRespBuilder.getDescriptorForType();
        Descriptors.FieldDescriptor hello = descriptor.findFieldByName("hello");

        DescriptorProtos.MessageOptions options = descriptor.getOptions();

        try {
            Demo.LogonRespMessage logonResp2 = Demo.LogonRespMessage.parseFrom(buf);
            Demo.UserInfo userInfo2 = logonResp2.getUserInfo();
            System.out.println("LogonResult = " + logonResp2.getLogonResult().toString() + " acctID = "
                    + userInfo2.getAcctID() + " name = " + userInfo2.getName() + " status = " + userInfo2.getStatus().toString());
        } catch (InvalidProtocolBufferException e) {
            e.printStackTrace();
        }
        System.out.println("Reading data from local file generated by C++");
        try {
            Demo.LogonRespMessage logonResp3 = Demo.LogonRespMessage.parseFrom(new FileInputStream("C:/Mine/LogonResp.dat"));
            Demo.UserInfo userInfo3 = logonResp3.getUserInfo();
            System.out.println("LogonResult = " + logonResp3.getLogonResult().toString() + " acctID = "
                    + userInfo3.getAcctID() + " name = " + userInfo3.getName() + " status = " + userInfo3.getStatus().toString());
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Message
    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    static class Person implements Serializable {
        private String name;
        private int age;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    static class Person2 {
        private String name;
        private int age;
        private int hello;
    }
}
